### ISSUE TITLE
Can't access "Customers" in the CP on fresh install

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-charge#10]
Fresh install of Statamic and charge. Go to cp then charge and try to click on customers. I get:
BadMethodCallException
Method Silentz\Charge\Http\Controllers\Web\CustomerController::index does not exist.
Full error:
https://flareapp.io/share/RmrejM5z#F61

PHP 7.4
Statamic 3.0.4
Mysql 8

**Comment by edalzell** [comment]
@twd3 fixed in latest release, please update.
