### ISSUE TITLE
When using subscription:cancel Stripe says webhook fails

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-charge#18]
When using {{ subscription:cancel :id="id" }} to cancel a current subscribers membership it does cancel it at Stripe but then stripe says the webhook for update subscription failed.

**Comment by edalzell** [comment]
What is in the Laravel log?

**Comment by twd3** [comment]
I was doing so much testing last night sorry. This is EXACTLY what happened...

I canceled the subscription via CP, it was set to cancel at the end of the month because that is how I have it setup (default). I then went to the Stripe dashboard and canceled that membership that was set to cancel at the end of the month, that's when the webhook failed...the CP never got that new canceled date. The end date stayed as canceling in a month.

**Comment by edalzell** [comment]
Anything your Laravel logs?

**Comment by edalzell** [comment]
What was the error in Stripe?

**Comment by edalzell** [comment]
I can't reproduce this, sorry. If it's still happening, please re-open
