### ISSUE TITLE
Can't access user tags inside of subscription:create tag

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-charge#19]
If you don't include an input with name="name" within the subscription:create tag the subscription fails. Since the user is logged in already I'd like that required name input pre-filled but using ```<input class="text-black" type="text" name="name" value="{{ user }}{{ name }}{{ /user }}">``` doesn't work so they have to retype their name. It does take the name under billing details in the script like:
```
                billing_details: {
                    name: '{{ user }}{{ name }}{{ /user }}',
                    email: '{{ user }}{{ email }}{{ /user }}'
                }
```

**Comment by edalzell** [comment]
That's  not the name of then person, it's the name of the subscription: https://laravel.com/docs/8.x/billing#creating-subscriptions.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/6069653/93038961-2e439980-f5fb-11ea-8c58-858f42deff44.png">

**Comment by edalzell** [comment]
@twd3 can you share the bit of template where the user is not coming through? I can't reproduce that part.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/6069653/93039448-613a5d00-f5fc-11ea-995e-9505a774f462.png">

<img width="378" alt="image" src="https://user-images.githubusercontent.com/6069653/93039462-6bf4f200-f5fc-11ea-9dc3-4bb889c7dbe0.png">

**Comment by twd3** [comment]
Ah ok, looks like if you put the {{ user }} loop outside of the subscription:create you have access. Also, thanks for clearing up that product vs. person name confusion.
