### ISSUE TITLE
User not getting assigned the plans role upon new subscription

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-charge#21]
Testing current version after a successful new subscription that newly created user is not assigned to the role configured for the plan they select. Nothing in logs...to recreate:

Create roles for plans first.

In charge config create plan/role mine has two:
```
    'roles_and_plans' => [
        [
            'plan' => 'price_1HPaqgGOTdHvGxxxxxx',
            'role' => 'active_member_yearly',
        ],
        [
            'plan' => 'price_1HPaqgGOTdHvGMxxxxxx',
            'role' => 'active_member_monthly',
        ],
    ],
```
Let them select on your subscription form:
```
    <label class="radio-inline">
      <input type="radio" name="plan" value="price_1HPaqgGOTdHvGxxxxxx">$10 per month
    </label>
    <label class="radio-inline">
      <input type="radio" name="plan" value="price_1HPaqgGOTdHvGMuxxxxxx">$99 per year
    </label>
```

Test subscribe new user then go check role for that user.

Statamic 3.0.10
Charge 4.0.6

**Comment by edalzell** [comment]
Fixed in 4.0.7
