### ISSUE TITLE
4.0.7 Update Won't Install

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-charge#23]
4.0.7 won't install on local. No errors, just won't come through. Marketplace says 4.0.6 as well. Github is good, says 4.0.7

**Comment by edalzell** [comment]
If you try from the command line `composer require silentz/charge` does it work?

**Comment by twd3** [comment]
Yeah, using require and not update worked.

**Comment by twd3** [comment]
Weird though the CP says I have an update but as you can see I don't?
![image](https://user-images.githubusercontent.com/16004958/93716913-9e887880-fb2f-11ea-84a6-b4b5503a7fdf.png)

**Comment by edalzell** [comment]
Likely a composer/packagist cache of some kind. Not really a charge issue.
