### ISSUE TITLE
Access level to Silentz\Charge\ServiceProvider::bootConfig() must be protected

### ISSUE THREAD

**Issue by hlopez22** [silentzco/statamic-charge#25]
Installed using `composer require silent/charge`

Returned this error: "Access level to Silentz\Charge\ServiceProvider::bootConfig() must be protected (as in class Statamic\Providers\AddonServiceProvider) or weaker"

**Comment by edalzell** [comment]
There is no such code in the latest version @hlopez22 : https://github.com/silentzco/statamic-charge/blob/v4.0.7/src/ServiceProvider.php

**Comment by edalzell** [comment]
Fixed in 4.1
