### ISSUE TITLE
Illuminate\Database\QueryException SQLSTATE[HY000]: General error: 1 no such table: subscriptions (SQL: select * from "subscriptions") 

### ISSUE THREAD

**Issue by nn-dmt** [silentzco/statamic-charge#29]
I'm running Butik with SQLite... does Charge not work with this? or is it misconfigured?

**Comment by edalzell** [comment]
Sounds like you haven't run the migrations.

**Comment by nn-dmt** [comment]
Wow quickest reply ever!

Is there documentation you have supporting the pre and post requisites to install? I couldn't find any on the addons page or on the github repo

**Comment by nn-dmt** [comment]
Nvm, ```php artisan migrate``` fixed it

**Comment by edalzell** [comment]
You're right, there's no readme, I can fix that. In the meantime: 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/6069653/103047112-494d7000-453f-11eb-9c4b-0069b57d16a1.png">

Docs are here: https://silentz.co/addons/charge/docs
