### ISSUE TITLE
Is it possible to use coupons with this?

### ISSUE THREAD

**Issue by beck24** [silentzco/statamic-charge#32]
I've tested this package for the basic subscription setup and it seems to be what we need for that, however we'll also need the ability to apply discount codes.
I did a quick grep for `discount` and `coupon` and only found a few hits for coupons in the tests which leads me to believe there's currently no support?

**Comment by edalzell** [comment]
Ya doesn't look like it supports it right now, but what's your timeline @beck24, I can likely get that added for ya!

**Comment by beck24** [comment]
it's an asap thing, I've been working on it this morning, looks like it shouldn't be too difficult.

In the SubscriptionController store function, accept a `promo_code` input and apply it if it exists:

    public function store(CreateSubscriptionRequest $request): RedirectResponse
    {
        try {
            $subscription = $request->user()
                ->newSubscription($request->name, $request->plan)
                ->quantity($request->quantity);

            if ($request->promo_code) {
                $subscription->withPromotionCode($request->promo_code);
            }
                
            $subscription->create($request->payment_method);

            return $this->withSuccess($subscription, $request);
        } catch (ApiErrorException $e) {
            return $this->withErrors($e->getError(), $request);
        } catch (IncompletePayment $e) {
            return $this->withIncomplete($e->payment->id, $request);
        }
    }

Then I've just added an endpoint to take a discount code eg. `DISCOUNT10` and fetch the ID from stripe, then I can pass that id into the store method with the plan.  Having it part of this package proper would be ideal though.

**Comment by edalzell** [comment]
If you'd like to do a PR I'll merge it in and release right quick!

**Comment by edalzell** [comment]
added in 4.2
