### ISSUE TITLE
Doesn't work on Laravel 9

### ISSUE THREAD

**Issue by michaelmannucci** [silentzco/statamic-charge#36]
As you already know, this wonderful plugin doesn't support Laravel 9 which is kind of a bummer... creating an issue because I don't understand how PR's work.

**Comment by edalzell** [comment]
Thanks for this. I’m on vacation right now, but I’ll get to this as soon as I can.

**Comment by edalzell** [comment]
> As you already know, this wonderful plugin doesn't support Laravel 9 which is kind of a bummer... creating an issue because I don't understand how PR's work.

Hi there @michaelmannucci, my plan would be to update to only require the latest (L9, PHP8.1, etc). Will that work for you?

**Comment by michaelmannucci** [comment]
Would that mean it wouldn't work for L9, PHP 8.0? Asking just because I'm curious.

Yes that would work for me :)

**Comment by edalzell** [comment]
> Would that mean it wouldn't work for L9, PHP 8.0? Asking just because I'm curious.
> 
> Yes that would work for me :)

Correct, only PHP8.1 would be supported.
