### ISSUE TITLE
ArgumentCountError

### ISSUE THREAD

**Issue by jeremydouglas** [silentzco/statamic-charge#7]
When submitting a subscription, I was receiving this error:

```
ArgumentCountError
Too few arguments to function App\User::newSubscription(), 1 passed in /Users/jeremyhoover/Sites/deboss-garage-api-v3/vendor/silentz/charge/src/Http/Controllers/Web/SubscriptionController.php on line 24 and exactly 2 expected 
```

I'm not a php dev, but I did a little source diving. [I changed this line](https://github.com/silentzco/statamic-charge/blob/master/src/Http/Controllers/Web/SubscriptionController.php#L24)

```
->newSubscription($request->name);
```

To this:
```
->newSubscription($request->name, $request->plans);
```

I'm now able to successfully create a subscription in Stripe.

**Comment by edalzell** [comment]
Fixed in https://github.com/silentzco/statamic-charge/commit/015a627b0bc4955039c9f7de26b92997d618143a
